# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoinsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripSchedulesDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('travelstartdate', models.DateField()),
                ('travelenddate', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('hashpw', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='tripschedulesdb',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertrip', to='main_app.UserDB'),
        ),
        migrations.AddField(
            model_name='joinsdb',
            name='trip_join',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_join', to='main_app.TripSchedulesDB'),
        ),
        migrations.AddField(
            model_name='joinsdb',
            name='user_join',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_join', to='main_app.UserDB'),
        ),
    ]
